# This is a basic workflow to help you get started with Actions

name: Test CNB Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      uses: niallthomson/cnb-build-action@master
      with:
        imageName: docker.io/niallthomson/cnb-test:sdasdasd
        builder: heroku/buildpacks:18
        publish: true
