# This is a basic workflow to help you get started with Actions

name: Test CNB Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pack
      run: wget https://github.com/buildpack/pack/releases/download/v0.9.0/pack-v0.9.0-linux.tgz && tar -xvf pack-v0.9.0-linux.tgz
    - name: Run pack
      run: ./pack build -p . --builder heroku/buildpacks:18